# Generated by Django 4.2.1 on 2023-08-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_alter_student_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(blank=True, max_length=550, null=True, upload_to='C:/Users/dell/OneDrive/Desktop/django1/djangoall/djangonew/dj1/'),
        ),
    ]
